CREATE DATABASE IF NOT EXISTS `zombieoutbreak`;
USE `zombieoutbreak`;

CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`identifier` VARCHAR(50) NOT NULL,
	`nickname` TINYTEXT NULL DEFAULT NULL,
	`information` LONGTEXT NULL DEFAULT NULL,
	`status` LONGTEXT NULL DEFAULT NULL,
	`traits` LONGTEXT NULL DEFAULT NULL,
	`skills` LONGTEXT NULL DEFAULT NULL,
	`group` VARCHAR(50) NULL DEFAULT NULL,
	`time` INT(11) NULL DEFAULT NULL,
	`money` LONGTEXT NULL DEFAULT NULL,
	`inventory` LONGTEXT NULL DEFAULT NULL,
	`skin` LONGTEXT NULL DEFAULT NULL,
	`position` LONGTEXT NULL DEFAULT NULL,

	PRIMARY KEY (`id`)
);